//this file used for testing APIs
//adviced for REST Client extension

POST http://localhost:4000/posts
content-type: application/json

{
    "title": "Seccond Post"
}

###
GET http://localhost:4000/posts
content-type: application/json

###
POST http://localhost:4001/posts/99009/comments
content-type: application/json

{
    "content": "Seccond Post second comment"
}

###
GET http://localhost:4001/posts/99009/comments
content-type: application/json

###
GET http://localhost:4001/posts/allComments
content-type: application/json
